INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (1, 'ヌードルヘブン', 1, 'house01.jpg', '手打ちラーメンと家庭料理が自慢のアットホームなラーメン店。親しみやすい雰囲気で、リーズナブルな価格で美味しいラーメンを提供。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (2, 'ボリューム亭', 2, 'house01.jpg', 'ボリューム満点の丼物が自慢の大衆食堂。一食でおなかいっぱいになること間違いなし。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (3, 'フライハウス', 3, 'house01.jpg', 'サクサクの揚げ物が豊富なファストフード店。特に唐揚げは絶品。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (4, 'ジャンクションバーガー', 4, 'house01.jpg', 'ジャンクフードの王道、巨大なハンバーガーが自慢のバーガーショップ。チーズとソースの組み合わせが最高。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (5, 'ピザ・パラダイス', 5, 'house01.jpg', '手作りピザが自慢のアットホームなピザ屋。トッピングのバリエーションが豊富。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (6, 'たこ焼き亭', 6, 'house01.jpg', '街角で人気の屋台風たこ焼き店。ジューシーでふわふわのたこ焼きが楽しめる。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (7, '肉ハブ', 7, 'house01.jpg', '串焼きと焼肉のダブル楽しみができる焼肉屋。手頃な価格でボリューム満点。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (8, 'シーフードラブ', 8, 'house01.jpg', '新鮮なシーフードが堪能できる海鮮居酒屋。刺身や焼き魚が豊富。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (9, 'ポテトプレジャー', 3, 'house01.jpg', 'さまざまなスタイルのポテトが楽しめるカジュアルポテト専門店。チーズやベーコントッピングがおすすめ。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (10, 'カレーの王様', 9, 'house01.jpg', 'スパイスたっぷりの本格的なカレーが自慢のカレー屋。辛さのレベルも選べる。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (11, 'オムライスランド', 10, 'house01.jpg', '豪快な盛り付けのオムライスが自慢の洋食屋。デミグラスソースが絶品。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (12, '和風焼肉街', 7, 'house01.jpg', '伝統的な和風の焼肉が楽しめる焼肉店。特製のたれが絶品。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (13, 'ビッグカレーパン屋', 11, 'house01.jpg', 'ジャンボサイズのカレーパンが自慢のベーカリー。サクサクの食感がクセになる。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (14, 'ハートフル寿司', 12, 'house01.jpg', '手軽に楽しめる寿司屋。ユニークな具材の寿司が揃う。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (15, 'うどん工房', 13, 'house01.jpg', '手打ちうどんが自慢のうどん専門店。出汁の香りが食欲をそそる。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (16, 'エッグワンダーランド', 10, 'house01.jpg', 'オムレツが主役のカジュアルダイニング。フワフワのオムレツにトッピングが自由自在。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (17, 'ラーメンジャングル', 1, 'house01.jpg', 'ラーメンのバリエーションが豊富なラーメンストリート。様々なスタイルのラーメンが楽しめる。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (18, 'チーズファンタジア', 14, 'house01.jpg', 'チーズ好きにはたまらないチーズ料理が楽しめるバー。様々な種類のチーズが堪能できる。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (19, 'ハンガーブレーカー', 7, 'house01.jpg', 'ボリューム満点のステーキが自慢のステーキハウス。肉好きにはたまらない一品。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (20, 'カフェ・モチモチ', 15, 'house01.jpg', 'もちもち食感が特徴の和風カフェ。和スイーツやもちもちパンが楽しめる。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (21, 'フルーツパラダイス', 15, 'house01.jpg', '季節のフルーツを贅沢に使用したデザートが楽しめるカフェ。フルーツ好きにおすすめ。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (22, 'ホットドッグワールド', 11, 'house01.jpg', 'カジュアルなホットドッグ専門店。変わり種のトッピングが特徴。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (23, 'サイドディッシュカフェ', 15, 'house01.jpg', 'サイドディッシュにこだわったカフェ。小皿料理を楽しみたい人におすすめ。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (24, 'パスタプレイス', 5, 'house01.jpg', '手打ちパスタが自慢のイタリアンレストラン。新鮮な具材と絶妙なソースが魅力。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (25, 'スイーツワンダーランド', 15, 'house01.jpg', '色とりどりのスイーツが楽しめるカフェ。デコレーションケーキやフルーツタルトが豊富。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (26, 'ベジータリアンハーバー', 10, 'house01.jpg', '野菜たっぷりのヘルシーな料理が楽しめるベジタリアンレストラン。新鮮な野菜の美味しさを堪能。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (27, 'カレーうどんストリート', 13, 'house01.jpg', 'カレーうどんがメインの食堂。スパイスと出汁の絶妙なバランスが魅力。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (28, 'チキンテリヤキハウス', 10, 'house01.jpg', '美味しいチキンテリヤキが味わえるファーストフード店。ボリュームたっぷりでリーズナブル。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (29, 'メキシカンタコスコーナー', 16, 'house01.jpg', 'カジュアルなメキシカンタコスが楽しめるスタンド。シャキシャキの野菜とスパイシーなソースが絶妙。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');
INSERT IGNORE INTO shop (id, name, category_id, image_name, description, price, holiday, postal_code, address, phone_number, opening_time, closing_time) VALUES (30, 'デザートドリームランド', 15, 'house01.jpg', 'ファンタジックなデザートが楽しめるカフェ。夢のようなスイーツが並ぶ。', 1000, '日', '073-0145', '北海道砂川市西五条南X-XX-XX', '012-345-678', '09:00', '21:00');


INSERT IGNORE INTO category (id, name) VALUES(1, 'ラーメン');
INSERT IGNORE INTO category (id, name) VALUES(2, '丼物');
INSERT IGNORE INTO category (id, name) VALUES(3, '揚げ物');
INSERT IGNORE INTO category (id, name) VALUES(4, 'ハンバーガー');
INSERT IGNORE INTO category (id, name) VALUES(5, 'イタリアン');
INSERT IGNORE INTO category (id, name) VALUES(6, 'たこ焼き');
INSERT IGNORE INTO category (id, name) VALUES(7, '焼肉');
INSERT IGNORE INTO category (id, name) VALUES(8, '居酒屋');
INSERT IGNORE INTO category (id, name) VALUES(9, 'カレー');
INSERT IGNORE INTO category (id, name) VALUES(10, 'ファミレス');
INSERT IGNORE INTO category (id, name) VALUES(11, 'パン');
INSERT IGNORE INTO category (id, name) VALUES(12, '寿司');
INSERT IGNORE INTO category (id, name) VALUES(13, 'うどん');
INSERT IGNORE INTO category (id, name) VALUES(14, 'バー');
INSERT IGNORE INTO category (id, name) VALUES(15, 'カフェ');
INSERT IGNORE INTO category (id, name) VALUES(16, 'メキシコ料理');

INSERT IGNORE INTO roles (id, name) VALUES (1, 'ROLE_GENERAL');
INSERT IGNORE INTO roles (id, name) VALUES (2, 'ROLE_MEMBERSHIP');
INSERT IGNORE INTO roles (id, name) VALUES (3, 'ROLE_ADMIN');

INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (1, '侍 太郎', 'サムライ タロウ', '101-0022', '東京都千代田区神田練塀町300番地', '090-1234-5678', 'taro.samurai@example.com', '$2a$10$2JNjTwZBwo7fprL2X4sv.OEKqxnVtsVQvuXDkI8xVGix.U3W5B7CO', 1, true);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (2, '侍 花子', 'サムライ ハナコ', '101-0022', '東京都千代田区神田練塀町300番地', '090-1234-5678', 'hanako.samurai@example.com', '$2a$10$2JNjTwZBwo7fprL2X4sv.OEKqxnVtsVQvuXDkI8xVGix.U3W5B7CO', 3, true);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (3, '侍 義勝', 'サムライ ヨシカツ', '638-0644', '奈良県五條市西吉野町湯川X-XX-XX', '090-1234-5678', 'yoshikatsu.samurai@example.com', 'password', 2, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (4, '侍 幸美', 'サムライ サチミ', '342-0006', '埼玉県吉川市南広島X-XX-XX', '090-1234-5678', 'sachimi.samurai@example.com', 'password', 2, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (5, '侍 雅', 'サムライ ミヤビ', '527-0209', '滋賀県東近江市佐目町X-XX-XX', '090-1234-5678', 'miyabi.samurai@example.com', 'password', 2, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (6, '侍 正保', 'サムライ マサヤス', '989-1203', '宮城県柴田郡大河原町旭町X-XX-XX', '090-1234-5678', 'masayasu.samurai@example.com', 'password', 2, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (7, '侍 真由美', 'サムライ マユミ', '951-8015', '新潟県新潟市松岡町X-XX-XX', '090-1234-5678', 'mayumi.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (8, '侍 安民', 'サムライ ヤスタミ', '241-0033', '神奈川県横浜市旭区今川町X-XX-XX', '090-1234-5678', 'yasutami.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (9, '侍 章緒', 'サムライ アキオ', '739-2103', '広島県東広島市高屋町宮領X-XX-XX', '090-1234-5678', 'akio.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (10, '侍 祐子', 'サムライ ユウコ', '601-0761', '京都府南丹市美山町高野X-XX-XX', '090-1234-5678', 'yuko.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (11, '侍 秋美', 'サムライ アキミ', '606-8235', '京都府京都市左京区田中西春菜町X-XX-XX', '090-1234-5678', 'akimi.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (12, '侍 信平', 'サムライ シンペイ', '673-1324', '兵庫県加東市新定X-XX-XX', '090-1234-5678', 'shinpei.samurai@example.com', 'password', 1, false);

INSERT IGNORE INTO reservations (id, shop_id, user_id, checkin_date, checkin_time, number_of_people ) VALUES (1, 1, 1, '2023-04-01', '12:00', 2);
INSERT IGNORE INTO reservations (id, shop_id, user_id, checkin_date, checkin_time, number_of_people ) VALUES (2, 2, 1, '2023-04-01', '12:00', 3);
INSERT IGNORE INTO reservations (id, shop_id, user_id, checkin_date, checkin_time, number_of_people ) VALUES (3, 3, 1, '2023-04-01', '12:00', 4);
INSERT IGNORE INTO reservations (id, shop_id, user_id, checkin_date, checkin_time, number_of_people ) VALUES (4, 4, 1, '2023-04-01', '12:00', 5);
INSERT IGNORE INTO reservations (id, shop_id, user_id, checkin_date, checkin_time, number_of_people ) VALUES (5, 5, 1, '2023-04-01', '12:00', 6);
INSERT IGNORE INTO reservations (id, shop_id, user_id, checkin_date, checkin_time, number_of_people ) VALUES (6, 6, 1, '2023-04-01', '12:00', 2);
INSERT IGNORE INTO reservations (id, shop_id, user_id, checkin_date, checkin_time, number_of_people ) VALUES (7, 7, 1, '2023-04-01', '12:00', 3);
INSERT IGNORE INTO reservations (id, shop_id, user_id, checkin_date, checkin_time, number_of_people ) VALUES (8, 8, 1, '2023-04-01', '12:00', 4);
INSERT IGNORE INTO reservations (id, shop_id, user_id, checkin_date, checkin_time, number_of_people ) VALUES (9, 9, 1, '2023-04-01', '12:00', 5);
INSERT IGNORE INTO reservations (id, shop_id, user_id, checkin_date, checkin_time, number_of_people ) VALUES (10, 10, 1, '2023-04-01', '12:00', 6);
INSERT IGNORE INTO reservations (id, shop_id, user_id, checkin_date, checkin_time, number_of_people ) VALUES (11, 11, 1, '2023-04-01', '12:00', 2);

INSERT IGNORE INTO favorites (id, shop_id, user_id) VALUES (1, 1, 1);
INSERT IGNORE INTO favorites (id, shop_id, user_id) VALUES (2, 2, 1);
INSERT IGNORE INTO favorites (id, shop_id, user_id) VALUES (3, 3, 1);
INSERT IGNORE INTO favorites (id, shop_id, user_id) VALUES (4, 4, 1);
INSERT IGNORE INTO favorites (id, shop_id, user_id) VALUES (5, 5, 1);
INSERT IGNORE INTO favorites (id, shop_id, user_id) VALUES (6, 6, 1);
INSERT IGNORE INTO favorites (id, shop_id, user_id) VALUES (7, 7, 1);
INSERT IGNORE INTO favorites (id, shop_id, user_id) VALUES (8, 8, 1);
INSERT IGNORE INTO favorites (id, shop_id, user_id) VALUES (9, 9, 1);
INSERT IGNORE INTO favorites (id, shop_id, user_id) VALUES (10, 10, 1);
INSERT IGNORE INTO favorites (id, shop_id, user_id) VALUES (11, 11, 1);
INSERT IGNORE INTO favorites (id, shop_id, user_id) VALUES (12, 12, 1);

INSERT IGNORE INTO reviews (id, shop_id, user_id, score, content) VALUES (1, 1, 1, 5, '素晴らしい滞在でした。また利用したいです。');
INSERT IGNORE INTO reviews (id, shop_id, user_id, score, content) VALUES (2, 1, 2, 4, '部屋が綺麗で、快適に過ごせました。');
INSERT IGNORE INTO reviews (id, shop_id, user_id, score, content) VALUES (3, 1, 3, 4, 'アクセスが良く、観光に最適でした。');
INSERT IGNORE INTO reviews (id, shop_id, user_id, score, content) VALUES (4, 1, 4, 5, 'スタッフが親切で、気持ちよく滞在できました。');
INSERT IGNORE INTO reviews (id, shop_id, user_id, score, content) VALUES (5, 1, 5, 4, '駅から近く、便利でした。');
INSERT IGNORE INTO reviews (id, shop_id, user_id, score, content) VALUES (6, 1, 6, 5, '周辺の飲食店が充実していて、楽しめました。');
INSERT IGNORE INTO reviews (id, shop_id, user_id, score, content) VALUES (7, 1, 7, 4, '宿泊費が手頃で、コストパフォーマンスが良かったです。');
INSERT IGNORE INTO reviews (id, shop_id, user_id, score, content) VALUES (8, 1, 8, 3, '静かな環境でゆっくり休めました。');
INSERT IGNORE INTO reviews (id, shop_id, user_id, score, content) VALUES (9, 1, 9, 4, '施設内の設備が充実していました。');
INSERT IGNORE INTO reviews (id, shop_id, user_id, score, content) VALUES (10, 1, 10, 5, 'Wi-Fiが快適で助かりました。');
INSERT IGNORE INTO reviews (id, shop_id, user_id, score, content) VALUES (11, 1, 11, 4, '清潔感があり、気持ちよく滞在できました。');
INSERT IGNORE INTO reviews (id, shop_id, user_id, score, content) VALUES (12, 1, 12, 5, '部屋が広く、ゆったり過ごせました。');